// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB80-6Ywc27sqKziks2vn08TeLzF6BO2E0',
    appId: '1:266828776832:web:ec77c6c1a5af8c868e6d65',
    messagingSenderId: '266828776832',
    projectId: 'nishauri-164c4',
    authDomain: 'nishauri-164c4.firebaseapp.com',
    storageBucket: 'nishauri-164c4.appspot.com',
    measurementId: 'G-RZ4897SPCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHXy40KGPvk6SalJI_qnPVTGXTtIdualU',
    appId: '1:266828776832:android:4f451e4500d5e9098e6d65',
    messagingSenderId: '266828776832',
    projectId: 'nishauri-164c4',
    storageBucket: 'nishauri-164c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_viqw29i469Bl_iWuGjC18TRKCMgh1AI',
    appId: '1:266828776832:ios:0c9838f44fc4c08c8e6d65',
    messagingSenderId: '266828776832',
    projectId: 'nishauri-164c4',
    storageBucket: 'nishauri-164c4.appspot.com',
    iosBundleId: 'org.kenyahmis.nishauri.nishauri',
  );
}
