// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCPK_MO0d0QUCHaBGqEylgzTZw9hWRDD8',
    appId: '1:921170637462:web:12ab142f7ee98c799b48b7',
    messagingSenderId: '921170637462',
    projectId: 'nishauri-new-2',
    authDomain: 'nishauri-new-2.firebaseapp.com',
    storageBucket: 'nishauri-new-2.appspot.com',
    measurementId: 'G-YME8KHDKM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDhK2nErRy_-SajzArNonosAo5nWaF9Us',
    appId: '1:921170637462:android:5e50f392a12562c59b48b7',
    messagingSenderId: '921170637462',
    projectId: 'nishauri-new-2',
    storageBucket: 'nishauri-new-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqmcg2s_uXkJwQq__3Lg6akV3NTbQf1Ps',
    appId: '1:921170637462:ios:9e081fc27a5afdf29b48b7',
    messagingSenderId: '921170637462',
    projectId: 'nishauri-new-2',
    storageBucket: 'nishauri-new-2.appspot.com',
    iosBundleId: 'org.kenyahmis.nishauri.nishauri',
  );

}