// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLVyv1jjsYc3KVRg22mgzLitYTAccYgNE',
    appId: '1:267862187023:web:6b51693fe50d4f0bc1977a',
    messagingSenderId: '267862187023',
    projectId: 'nishauri-new',
    authDomain: 'nishauri-new.firebaseapp.com',
    storageBucket: 'nishauri-new.appspot.com',
    measurementId: 'G-EYY0YEJG62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKDyCG0apB4uUJogcl-3vpSuIOlyrqRWE',
    appId: '1:267862187023:android:9630eda52e0b0fa5c1977a',
    messagingSenderId: '267862187023',
    projectId: 'nishauri-new',
    storageBucket: 'nishauri-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqMTJ-UYVEsFZBV72Woprz4G2sHCqEKsQ',
    appId: '1:267862187023:ios:f292a3afa35839afc1977a',
    messagingSenderId: '267862187023',
    projectId: 'nishauri-new',
    storageBucket: 'nishauri-new.appspot.com',
    iosBundleId: 'org.kenyahmis.nishauri.nishauri',
  );

}